version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  # Maintain dependencies within Dockerfiles
  - package-ecosystem: 'docker'
    directory: '/14/'
    schedule:
      interval: 'daily'
    ignore:
      - update-types: ['version-update:semver-major']
  - package-ecosystem: 'docker'
    directory: '/15/'
    schedule:
      interval: 'daily'
    ignore:
      - update-types: ['version-update:semver-major']
